# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  configure:
    steps:
      - run:
          command: |
            ./buildconf
            ./configure --enable-warnings --enable-werror --with-openssl

  build:
    steps:
      - run: make

  test:
    steps:
      - run: TFLAGS="-l" make test-nonflaky  | pcregrep -o1 "test (\d+)\.\.\." | circleci tests split > tests.txt
      - run: TFLAGS="$(cat tests.txt | tr '\n' ' ')" make test-nonflaky

executors:
  docker:
    docker:
      - image: cimg/base:2021.05

jobs:
  test:
    executor: docker
    parallelism: 4
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install libtool autoconf automake pkg-config libssl-dev pcregrep
          name: install prereqs
      - configure
      - build
      - test


workflows:
  all:
    jobs:
      - test
